// <auto-generated />
using System;
using LaMesaDelDuque.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LaMesaDelDuque.Infraestructura.Migrations
{
    [DbContext(typeof(LaMesaDelDuqueDbContext))]
    [Migration("20260515120000_Sprint2_ColumnasFaltantes")]
    partial class Sprint2_ColumnasFaltantes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot mínimo requerido — el modelo completo está en LaMesaDelDuqueDbContextModelSnapshot
        }
    }
}
